from __future__ import annotations

import argparse
import json
import struct
import time
import zlib
from contextlib import nullcontext
from pathlib import Path
from typing import Any

import numpy as np
import torch

from compressai_nano import get_model, infer_model_variant_from_checkpoint
from decode_cnz import crop_to_size, resize_tensor_to_size, tensor_to_image


def sync_device(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.synchronize(device)


def now_synced(device: torch.device) -> float:
    sync_device(device)
    return time.perf_counter()


def make_autocast(device: torch.device, enabled: bool):
    if enabled and device.type == "cuda":
        return torch.amp.autocast("cuda", dtype=torch.float16)
    return nullcontext()


def load_checkpoint(model: torch.nn.Module, checkpoint: Path) -> None:
    raw = torch.load(checkpoint, map_location="cpu")
    state_dict = raw.get("state_dict", raw) if isinstance(raw, dict) else raw
    missing, unexpected = model.load_state_dict(state_dict, strict=False)
    print(f"missing_keys: {len(missing)}")
    print(f"unexpected_keys: {len(unexpected)}")


HMS_HEADER_FORMAT = "<4sIIIIIQQQQ"
HMS_HEADER_SIZE = struct.calcsize(HMS_HEADER_FORMAT)
HMS_MAGIC = b"HMS1"
CODEC_NONE = 1
CODEC_ZLIB = 2
DTYPE_INT16 = 1
DTYPE_INT32 = 2


def unpack_symbols(raw: bytes, dtype_code: int, shape: tuple[int, int, int, int]) -> torch.Tensor:
    if dtype_code == DTYPE_INT16:
        dtype = np.dtype("<i2")
    elif dtype_code == DTYPE_INT32:
        dtype = np.dtype("<i4")
    else:
        raise ValueError(f"unsupported dtype code: {dtype_code}")
    expected = int(np.prod(shape)) * dtype.itemsize
    if len(raw) != expected:
        raise ValueError(f"raw symbol size mismatch: got {len(raw)}, expected {expected}")
    array = np.frombuffer(raw, dtype=dtype).astype(np.int32, copy=True).reshape(shape)
    return torch.from_numpy(array)


def decompress_payload(payload: bytes, codec_code: int, expected_raw_size: int) -> bytes:
    if codec_code == CODEC_NONE:
        raw = payload
    elif codec_code == CODEC_ZLIB:
        raw = zlib.decompress(payload)
    else:
        raise ValueError(f"unsupported HMS codec code: {codec_code}")
    if len(raw) != expected_raw_size:
        raise ValueError(f"decompressed size mismatch: got {len(raw)}, expected {expected_raw_size}")
    return raw


def load_hms(path: Path) -> tuple[torch.Tensor, torch.Tensor, dict[str, Any]]:
    data = path.read_bytes()
    if len(data) < HMS_HEADER_SIZE:
        raise ValueError(f"{path} is too small for HMS header")
    (
        magic,
        version,
        header_json_size,
        codec_code,
        y_dtype,
        z_dtype,
        y_raw_size,
        z_raw_size,
        y_payload_size,
        z_payload_size,
    ) = struct.unpack(HMS_HEADER_FORMAT, data[:HMS_HEADER_SIZE])
    if magic != HMS_MAGIC:
        raise ValueError(f"invalid HMS magic: {magic!r}")
    if version != 1:
        raise ValueError(f"unsupported HMS version: {version}")
    offset = HMS_HEADER_SIZE
    header_end = offset + int(header_json_size)
    y_end = header_end + int(y_payload_size)
    z_end = y_end + int(z_payload_size)
    if z_end != len(data):
        raise ValueError("HMS payload size mismatch")
    metadata = json.loads(data[offset:header_end].decode("utf-8"))
    y_shape = tuple(int(v) for v in metadata["y_shape"])
    z_shape = tuple(int(v) for v in metadata["z_shape"])
    y_raw = decompress_payload(data[header_end:y_end], codec_code, int(y_raw_size))
    z_raw = decompress_payload(data[y_end:z_end], codec_code, int(z_raw_size))
    return unpack_symbols(y_raw, y_dtype, y_shape), unpack_symbols(z_raw, z_dtype, z_shape), metadata


def load_npz(path: Path) -> tuple[torch.Tensor, torch.Tensor, dict[str, Any]]:
    data = np.load(path, allow_pickle=False)
    if "y_symbols" not in data or "z_symbols" not in data:
        raise ValueError(f"{path} must contain y_symbols and z_symbols")
    metadata: dict[str, Any] = {}
    if "metadata" in data:
        metadata = json.loads(str(data["metadata"]))
    y_symbols = torch.from_numpy(np.asarray(data["y_symbols"]).astype(np.int32, copy=False))
    z_symbols = torch.from_numpy(np.asarray(data["z_symbols"]).astype(np.int32, copy=False))
    return y_symbols, z_symbols, metadata


def load_package(path: Path) -> tuple[torch.Tensor, torch.Tensor, dict[str, Any]]:
    with path.open("rb") as handle:
        magic = handle.read(4)
    if magic == HMS_MAGIC:
        return load_hms(path)
    return load_npz(path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Decode a hyper_ms_nano reference .npz/.hms package back to an image using "
            "the PyTorch hyper decoder and image decoder."
        )
    )
    parser.add_argument("input", type=Path, help=".npz or .hms generated by RK3588 hyper_ms scripts")
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("recon_hyper_ms.png"))
    parser.add_argument("--device", choices=("auto", "cuda", "cpu"), default="auto")
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--half", action="store_true", help="Use CUDA FP16 autocast for h_s and decoder.")
    parser.add_argument(
        "--channels-last",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use channels-last memory format on CUDA.",
    )
    parser.add_argument(
        "--resize-to-source",
        action="store_true",
        help="Resize output back to source_h/source_w from package metadata.",
    )
    parser.add_argument(
        "--resize-mode",
        choices=("nearest", "bilinear", "bicubic"),
        default="bicubic",
    )
    parser.add_argument("--timing", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.cpu:
        args.device = "cpu"
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested, but torch.cuda.is_available() is false")
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    if args.half and device.type != "cuda":
        raise RuntimeError("--half is only supported with CUDA")

    if device.type == "cuda":
        torch.backends.cudnn.benchmark = True
        print(f"device: cuda ({torch.cuda.get_device_name(device)})")
    else:
        print("device: cpu")

    raw = torch.load(args.checkpoint, map_location="cpu")
    model_variant = infer_model_variant_from_checkpoint(raw)
    model = get_model(model_variant=model_variant).to(device).eval()
    if getattr(model, "supports_cnz_v4", False):
        raise RuntimeError(
            f"{model_variant} is the legacy CNZ4 model. Use decode_cnz.py for CNZ4, "
            "not decode_hyper_ms_npz.py."
        )
    if not all(hasattr(model, name) for name in ("entropy_bottleneck_z", "hyper_decoder", "decoder")):
        raise RuntimeError(f"{model_variant} does not look like a hyperprior model")

    if device.type == "cuda" and args.channels_last:
        model = model.to(memory_format=torch.channels_last)
    if args.half:
        model = model.half()

    t0 = now_synced(device)
    load_checkpoint(model, args.checkpoint)
    t1 = now_synced(device)

    y_symbols, z_symbols, metadata = load_package(args.input)
    y_symbols = y_symbols.to(device=device)
    z_symbols = z_symbols.to(device=device)
    t2 = now_synced(device)

    with torch.inference_mode():
        z_hat = model.entropy_bottleneck_z.dequantize(
            z_symbols,
            dtype=torch.float16 if args.half else torch.float32,
            device=device,
        )
        with make_autocast(device, args.half):
            hyper = model.hyper_decoder(z_hat)
            if not isinstance(hyper, tuple) or len(hyper) != 2:
                raise RuntimeError("expected hyper_decoder(z_hat) -> (scales_y, means_y)")
            _scales_y, means_y = hyper
            y_hat = model.conditional_entropy_y.dequantize(
                y_symbols,
                means_y=means_y,
                dtype=torch.float16 if args.half else torch.float32,
                device=device,
            )
            x_hat = model.decoder(y_hat)
        t3 = now_synced(device)

        orig_h = int(metadata.get("orig_h", metadata.get("padded_h", x_hat.shape[-2])))
        orig_w = int(metadata.get("orig_w", metadata.get("padded_w", x_hat.shape[-1])))
        x_hat = crop_to_size(x_hat, (orig_h, orig_w))
        print(f"cropped_to_encoded_size: {(orig_h, orig_w)}")

        if args.resize_to_source:
            if "source_h" not in metadata or "source_w" not in metadata:
                raise ValueError("metadata missing source_h/source_w; cannot --resize-to-source")
            source_size = (int(metadata["source_h"]), int(metadata["source_w"]))
            x_hat = resize_tensor_to_size(x_hat, source_size, mode=args.resize_mode)
            print(f"resized_to_source_size: {source_size} using {args.resize_mode}")
        t4 = now_synced(device)

    tensor_to_image(x_hat, args.output)
    t5 = now_synced(device)

    print(f"input: {args.input}")
    print(f"checkpoint: {args.checkpoint}")
    print(f"model_variant: {model_variant}")
    print(f"y_symbols_shape: {tuple(int(v) for v in y_symbols.shape)}")
    print(f"z_symbols_shape: {tuple(int(v) for v in z_symbols.shape)}")
    if metadata:
        print(f"package_model_variant: {metadata.get('model_variant')}")
        print(f"package_bpp_hint: {args.input.stat().st_size * 8 / max(1, orig_h * orig_w):.4f}")
    if args.timing:
        print(f"timing_load_checkpoint_ms={(t1 - t0) * 1000:.3f}")
        print(f"timing_load_npz_ms={(t2 - t1) * 1000:.3f}")
        print(f"timing_decode_model_ms={(t3 - t2) * 1000:.3f}")
        print(f"timing_crop_resize_ms={(t4 - t3) * 1000:.3f}")
        print(f"timing_save_image_ms={(t5 - t4) * 1000:.3f}")
        print(f"timing_total_ms={(t5 - t0) * 1000:.3f}")
    print(f"saved: {args.output}")


if __name__ == "__main__":
    main()
